# Generated by Django 2.2 on 2019-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_squashed_0033_auto_20190507_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_value'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
