# Generated by Django 2.2 on 2019-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20190507_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort_value',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чем меньше значение, тем раньше выводится категория в меню', verbose_name='Порядок сортировки'),
        ),
    ]
