# Generated by Django 2.2 on 2019-05-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20190511_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainpageSettings',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
