# Generated by Django 2.2 on 2019-05-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20190511_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infopage',
        ),
    ]
