# Generated by Django 2.2 on 2019-05-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_delete_infopage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
