# Generated by Django 2.2 on 2019-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainpageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title главной страницы')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='Description главной страницы')),
                ('firstscreen_title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок на первом экране главной страницы')),
                ('firstscreen_text', models.TextField(blank=True, verbose_name='Текст на первом экране главной страницы')),
                ('firstscreen_img', models.ImageField(blank=True, upload_to='mainpage-background/', verbose_name='Бэкграунд первого экрана')),
                ('firstscreen_button_txt', models.CharField(blank=True, max_length=20, verbose_name='Надпись на кнопке')),
                ('firstscreen_button_color', models.CharField(blank=True, max_length=6, verbose_name='Цвет кнопки (HEX)')),
                ('firstscreen_button_hover_color', models.CharField(blank=True, max_length=6, verbose_name='Цвет кнопки при наведении мыши (HEX)')),
                ('cat_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок блока категорий')),
                ('cat_text', models.CharField(blank=True, max_length=100, verbose_name='Текст блока категорий')),
                ('about_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок блока О нас')),
                ('about_text', models.TextField(blank=True, verbose_name='Текст блока О нас')),
                ('about_img', models.ImageField(blank=True, upload_to='about-img/', verbose_name='Картинка блока О нас')),
                ('subscribe_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок блока подписки')),
                ('subscribe_text', models.TextField(blank=True, verbose_name='Текст блока подписки')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='logo/', verbose_name='Лого в шапке')),
                ('logo_width_desktop', models.IntegerField(verbose_name='Ширина логотипа десктоп(в px)')),
                ('logo_width_mobile', models.IntegerField(verbose_name='Ширина логотипа в мобильном меню(в px)')),
                ('footer_mail', models.CharField(max_length=50, verbose_name='Почта в подвале')),
                ('footer_social', models.TextField(verbose_name='Ссылки на соцсети')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
