# Generated by Django 2.2 on 2019-05-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infopage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Символльный код')),
                ('content', models.TextField(max_length=3000, verbose_name='Содержание')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Выводить в верхнем меню')),
                ('active', models.BooleanField(default=True, help_text='Отключенные материалы исчезают с сайта', verbose_name='Материал активен')),
                ('seo_title', models.CharField(blank=True, help_text='Это поле будет заголовком страницы в браузере. Очень важное поле для поисковых систем. Заполнять нужно с умом', max_length=200, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, help_text='Мета-описание. Пользователи его не видят, но поисковикам важно, чтобы оно было заполнено. Пустым оставлять можно, но не рекомендуется.', max_length=400, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Информационная страница',
                'verbose_name_plural': 'Информационные страницы',
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Общие настройки сайта', 'verbose_name_plural': 'Общие настройки сайта'},
        ),
    ]
